# Instructions: instantiate and uncomment below lines with <MISSING> values, then delete this line.

# This configuration file is read by lab_interfaces.CourseAuth.from_secrets.
# Each section below is optional configuration.
# It is required when the corresponding system is used.

# Canvas authentication.
# Used for synchronization with the Canvas course.
[canvas]
#auth_token = "<MISSING>"

# Chalmers GitLab authentication.
# Used for managing the labs.
[gitlab]
#private_token = "<MISSING>"

# Optional, required for webhook features.
# Secret token to set and check for webhook notifications.
# The value does not matter, but must be consistent over multiple invocations that use the same webhooks.
#webhook_secret_token = "<MISSING>"

# Google credentials.
# Recommended to be for a service account.
# Used for maintaining the grading overview spreadsheet.
[google.credentials]
tyype = "service_account"
#project_id = "<MISSING>"
#private_key_id = "<MISSING>"
#private_key = """
#<MISSING>
#"""
#client_email = "<MISSING>"
#client_id = "<MISSING>"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
#client_x509_cert_url = "<MISSING>"

# Credentials for Chalmers PDB.
# Used for translating a personnummer to a CID (used for GU students).
[pdb]
#username = "<MISSING>"
#password = "<MISSING>"
