[[entry]]
source="/requests"
target="lp4/unified-live-submissions-table.html"
password="fnH53BB/0LnrY9Sy"

[[entry]]
source="/loader"
target="lp4/unified-live-submissions-table-loader.html"
password="fnH53BB/0LnrY9Sy"

[[entry]]
source="/lab-1/requests"
target="lp4/lab-1/live-submissions-table.html"
password="fnH53BB/0LnrY9Sy"

[[entry]]
source="/lab-2/requests"
target="lp4/lab-2/live-submissions-table.html"
password="fnH53BB/0LnrY9Sy"

[[entry]]
source="/lab-3/requests"
target="lp4/lab-3/live-submissions-table.html"
password="fnH53BB/0LnrY9Sy"

[[entry]]
source="/lab-4/requests"
target="lp4/lab-4/live-submissions-table.html"
password="fnH53BB/0LnrY9Sy"
